CREATE DATABASE ECOM; -- CREATING DATABASE
USE ECOM;  -- USING THE BATABASE

-- CREATING TABLES
-- CUSTOMERS

CREATE TABLE CUSTOMERS(
CUST_ID VARCHAR(255),
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(255),
EMAIL VARCHAR(250),
GENDER ENUM("MALE","FEMALE","OTHERS"),
PHONE VARCHAR(10),
ANNUAL_INCOME DECIMAL(10,2));

SELECT * 
FROM CUSTOMER;

DESCRIBE CUSTOMER;